import { MOODS, FEEDBACK, recommend, tasteProfile, discovery, entityId, mealKey } from './core.mjs';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const moneyExact = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2,maximumFractionDigits:2}).format(value);
const date = value => new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'});
const captions = {Comfort:'Warm. Familiar. Unhurried.',Light:'A little less. Still satisfying.',Spicy:'A little fire at the table.',Indulgent:'Make room for a treat.',Familiar:'The comfort of knowing.',Explore:'A new flavour, your way.',Quick:'Good food. Less waiting.','Proper meal':'A plate that feels complete.'};
let state = {orders:[],feedback:[],settings:{},mood:'Comfort',hunger:'Regular',budget:0,view:'tonight',user:null,loading:false,error:'',demo:false}, result, historyLimit=25, selectedChoice=null, selectedOrder=null;
let auth,db,api,root,unsubs=[],sessionGeneration=0;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function link(query,provider='zomato'){return provider==='maps'?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`:`https://www.zomato.com/search?q=${encodeURIComponent(query)}`}
function sourceUrl(order){return `https://mail.google.com/mail/u/0/#all/${order.source.gmailMessageId}`}
function showView(name){if(!['tonight','taste','history','discover'].includes(name))name='tonight';state.view=name;$$('.view').forEach(el=>el.classList.toggle('active',el.dataset.page===name));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===name));if(location.hash!==`#${name}`)history.replaceState(null,'',`#${name}`);render();window.scrollTo({top:0,behavior:'instant'})}
function context(){return {mood:state.mood,hunger:state.hunger,budget:state.budget,vegetarian:state.settings.vegetarian!==false}}
function render(){
 result=recommend(state.orders,state.feedback,context());
 $('#moods').innerHTML=MOODS.map(m=>`<button class="mood-chip ${state.mood===m?'active':''}" data-mood="${esc(m)}" aria-pressed="${state.mood===m}">${esc(m)}</button>`).join('');
 $('#moodWord').textContent=state.mood;$('#moodCaption').textContent=captions[state.mood];$('#mealStage').dataset.mood=state.mood;
 $('#authButton').textContent=state.demo?'Sample mode':state.user?(state.user.displayName?.split(' ')[0]||'Account'):'Sign in';
 const hour=Number(new Intl.DateTimeFormat('en-GB',{hour:'numeric',hourCycle:'h23',timeZone:'Asia/Kolkata'}).format(new Date()));
 $('#greeting').textContent=state.demo?'Sample table · fictional food memory':`${hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'}${state.user?.displayName?', '+state.user.displayName.split(' ')[0]:''}. Your table is ready.`;
 $('#memoryStatus').classList.toggle('sync-error',!!state.error);
 $('#memoryStatus').textContent=state.error?'Sync failed · retry':state.loading?'Opening your memory…':state.demo?'Sample · no cloud writes':state.user?`${result.profile.orderCount} meals remembered${state.truncated?' · recent 500':''}`:'Connect your food memory';
 $('#choiceHeading').textContent=state.mood==='Explore'?'A little outside the usual.':state.mood==='Light'?'Something a little lighter.':state.mood==='Spicy'?'A little heat, perhaps.':'For you, right now.';
 $('#choiceMeta').textContent=state.user||state.demo?`${state.mood.toLowerCase()} · ${state.hunger.toLowerCase()} appetite`:'Your history is the starting point';
 renderChoices();renderMemory();if(state.view==='taste')renderTaste();if(state.view==='history')renderHistory();if(state.view==='discover')renderDiscover();
}
function empty(title,copy,button=''){return `<div class="empty-panel"><div><h3>${title}</h3><p>${copy}</p></div>${button}</div>`}
function renderChoices(){
 const el=$('#choices');
 if(state.loading&&!state.orders.length){el.innerHTML=empty('Setting your table…','Opening your private order history.');return}
 if(!state.user&&!state.demo){el.innerHTML=empty('Your taste starts with your history.','Sign in with your PTI account to see your imported Zomato orders and personal food choices.','<button class="primary" data-action="login">Open my food memory</button>');return}
 if(state.error&&!state.orders.length){el.innerHTML=empty('Your memory could not be opened.',esc(state.error),'<button class="primary" data-action="reload">Try again</button>');return}
 if(!result.choices.length){el.innerHTML=empty(state.orders.length?'Nothing fits these filters yet.':'A clean plate. A new beginning.',esc(result.note),'<button class="secondary" data-action="settings">Memory & connections</button>');return}
 el.innerHTML=result.choices.map((c,i)=>{
  const names=c.items.slice(0,2).map(x=>x.name).join(' + '),extra=c.items.length>2?` + ${c.items.length-2} more`:'';
  return `<article class="choice"><div class="choice-top"><span class="mode">${esc(c.mode)}</span><span class="choice-number">0${i+1}</span></div><h3>${esc(names)}${esc(extra)}</h3><p class="restaurant">${esc(c.restaurant)}</p><p class="why">${esc(c.count>1?`${c.count} orders to come back to.`:'A meal from your own history.')} ${esc(c.moodFit?`A ${state.mood.toLowerCase()} direction.`:c.reasons.find(r=>r.startsWith('Last ordered'))||'')}</p><div class="choice-bottom"><span class="price">Previously ${money(c.previousTotal)} / basket</span><button data-choice="${i}">Why this fits</button></div></article>`;
 }).join('')+`<p class="choice-note">${esc(result.note)} ${state.mood==='Light'?'“Light” uses dish-name hints, not nutrition estimates.':''}</p>`;
}
function renderMemory(){
 const p=result.profile;
 $('#memoryStrip').innerHTML=[[''+p.orderCount,'unique orders'],[''+p.restaurants.length,'restaurants'],[''+p.dishes.length,'dishes remembered']].map(([n,label])=>`<div class="memory-stat"><strong>${n}</strong><span>${label}</span></div>`).join('');
 const last=[...state.orders].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt))[0];
 $('#lastMeal').innerHTML=last?`<p class="eyebrow">LAST AT YOUR TABLE</p><button data-order="${esc(last.id)}">${esc(last.restaurantName)}</button><span>${date(last.receivedAt)} · ${esc(last.items.slice(0,2).map(x=>x.name).join(' + '))}</span>`:'<p class="eyebrow">A MEMORY THAT GROWS</p><p>Each receipt becomes a little more context.</p>';
}
function bars(items,total){return items.slice(0,7).map(x=>`<div class="bar-row"><span>${esc(x.name)}</span><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="width:${Math.max(2,x.count/Math.max(1,total)*100)}%"></div></div><strong>${x.count}</strong></div>`).join('')}
function renderTaste(){
 const p=result.profile;if(!p.orderCount){$('#tasteContent').innerHTML=empty('Your taste is still taking shape.','Open your food memory to see the dishes, cuisines and places you return to.');return}
 $('#tasteContent').innerHTML=`<div class="taste-grid"><div><section class="taste-section"><h2>Where your taste leans</h2>${bars(p.cuisines,p.orderCount)}<p class="taste-note">Counts are orders containing each cuisine. A mixed meal can appear in more than one cuisine. Labels are inferred from dish names.</p></section><section class="taste-section"><h2>The dishes you return to</h2>${p.dishes.slice(0,10).map(d=>`<div class="food-rank"><div>${esc(d.name)}<span>${esc(d.cuisine)} · last ${date(d.lastAt)}</span></div><strong>${d.count} orders</strong></div>`).join('')}</section></div><div><section class="taste-section"><h2>A hint of your flavour palette</h2>${bars(p.tags,p.orderCount)}<p class="taste-note">These are name-based hints, not tasted flavours or measured ingredient preferences.</p></section><section class="taste-section"><h2>Your familiar tables</h2>${p.restaurants.slice(0,6).map(r=>`<div class="food-rank"><div>${esc(r.name)}<span>${money(r.averagePaid)} average past basket</span></div><strong>${r.count} orders</strong></div>`).join('')}</section><div class="feedback-teaser"><h3>Receipts tell only half the story.</h3><p class="hint">You have left ${state.feedback.length} meal reactions. Loved, good, okay or “don’t suggest again” helps turn repeats into preferences.</p><button class="text-button" data-view="history">Add a little meaning</button></div></div></div><p class="taste-note">${date(p.firstAt)} to ${date(p.lastAt)} · ${money(p.totalPaid)} in imported delivered receipts. Some baskets were shared; this is order history, not individual intake. Time patterns use receipt timestamps in India.</p>`;
}
function renderHistory(){
 const needle=$('#historySearch').value.toLowerCase().trim(),status=$('#historyStatus').value;
 const rows=[...state.orders].filter(o=>(status==='all'||o.status===status)&&(!needle||[o.restaurantName,...o.items.map(i=>i.name)].join(' ').toLowerCase().includes(needle))).sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt));
 let month='';$('#historyList').innerHTML=rows.slice(0,historyLimit).map(o=>{
  const m=new Date(o.receivedAt).toLocaleDateString('en-IN',{month:'long',year:'numeric',timeZone:'Asia/Kolkata'}),head=m!==month?`<h2 class="history-month">${m}</h2>`:'';month=m;
  const time=new Intl.DateTimeFormat('en-IN',{day:'2-digit',weekday:'short',timeZone:'Asia/Kolkata'}).formatToParts(new Date(o.receivedAt)), day=time.find(x=>x.type==='day').value,weekday=time.find(x=>x.type==='weekday').value;
  const f=state.feedback.find(f=>f.targetKey===mealKey(o));
  return `${head}<button class="order-row" data-order="${esc(o.id)}"><span class="order-date"><strong>${day}</strong>${weekday}</span><div><h3>${esc(o.restaurantName)}</h3><p>${esc(o.items.map(x=>`${x.quantity} × ${x.name}`).join(' · '))}</p></div><span class="order-cost">${money(o.total)}<span>${f?esc(f.reaction==='never'?'Excluded':f.reaction):esc(o.status)}</span></span></button>`;
 }).join('')||empty('No meals here yet.',needle?'Try a different dish or restaurant.':'Your imported receipts will appear here.');
 $('#moreHistory').hidden=rows.length<=historyLimit;
}
function renderDiscover(){const directions=discovery(result.profile,state.mood);$('#discoveryList').innerHTML=directions.map((d,i)=>`<article class="discovery-card"><span class="discovery-number">0${i+1}</span><div><h2>${esc(d.name)}</h2><p>${esc(d.dish)}</p></div><p class="discovery-basis">${esc(d.basis)}.<br><strong>Idea to investigate · no menu verified</strong></p><a class="secondary" target="_blank" rel="noopener noreferrer" href="${link(d.query,'maps')}">Look nearby</a></article>`).join('')+'<p class="taste-note">These are curated vegetarian exploration ideas, ordered using your dish-name signals. They are not confirmed menu items, restaurant endorsements or availability promises.</p>'}
function openChoice(index){selectedChoice=result.choices[+index];selectedOrder=null;if(!selectedChoice)return;const c=selectedChoice;$('#detailContent').innerHTML=`<p class="eyebrow">${esc(c.mode)} · FROM YOUR HISTORY</p><h2>${esc(c.title)}</h2><p>${esc(c.restaurant)}</p><h3>Why it appeared</h3><ul>${c.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><p class="hint">${c.evidenceOrderIds.length} receipt${c.evidenceOrderIds.length===1?'':'s'} support this choice. “Ordered” does not automatically mean “enjoyed”.</p><div class="detail-items">${c.items.map(i=>`<div class="detail-item"><span>${esc(i.name)}</span><span>${esc(i.cuisine)}</span></div>`).join('')}</div><p class="hint">Ingredients, current menu and availability are unverified. Confirm vegetarian ingredients when ordering.</p>${feedbackForm(c.targetKey)}<div class="dialog-actions"><a class="primary" target="_blank" rel="noopener noreferrer" href="${link(c.restaurant+' Kharghar')}">Find in Zomato</a><button class="secondary" data-order="${esc(c.evidenceOrderIds[0])}">View a receipt</button></div>`;$('#detailDialog').showModal()}
function feedbackForm(targetKey){const f=state.feedback.find(x=>x.targetKey===targetKey);return `<h3>How does this meal feel to you?</h3><div class="feedback-options">${[['loved','Loved'],['good','Good'],['okay','Okay'],['never','Don’t suggest again']].map(([value,label])=>`<button data-feedback="${value}" data-key="${esc(targetKey)}" class="${f?.reaction===value?'active':''}" aria-pressed="${f?.reaction===value}">${label}</button>`).join('')}</div><label class="feedback-note">A note, if you like<input id="feedbackNote" maxlength="1000" value="${esc(f?.note||'')}" placeholder="Too rich, loved the spice, want this again…"></label><button class="text-button" data-action="save-note">Save note</button><p class="hint">Your chosen food mood: ${esc(state.mood)}. Reactions are saved to your private memory.</p>`}
function openOrder(id){const order=state.orders.find(o=>o.id===id);if(!order)return;selectedOrder=order;selectedChoice=null;const f=state.feedback.find(x=>x.targetKey===mealKey(order));$('#detailContent').innerHTML=`<p class="eyebrow">ZOMATO RECEIPT · ${esc(order.orderId)}</p><h2>${esc(order.restaurantName)}</h2><p>${date(order.receivedAt)} · ${esc(order.status)}</p><p class="hint">${esc(order.outlet)}</p><div class="detail-items">${order.items.map(i=>`<div class="detail-item"><span>${esc(i.name)}</span><strong>× ${i.quantity}</strong></div>`).join('')}</div><div class="detail-total"><span>Total paid</span><span>${moneyExact(order.total)}</span></div><p class="hint">Full basket total; quantities may include other diners. Original dish wording is retained in the source record.</p>${feedbackForm(mealKey(order))}<a class="source-link" href="${sourceUrl(order)}" target="_blank" rel="noopener noreferrer">Open original email</a>`;if(!$('#detailDialog').open)$('#detailDialog').showModal()}
async function saveFeedback(reaction,targetKey){
 if(!FEEDBACK.includes(reaction))return;
 const note=$('#feedbackNote')?.value||'', id=entityId(targetKey),existing=state.feedback.find(f=>f.targetKey===targetKey),data={id,targetKey,reaction,note,mood:state.mood,createdAt:new Date().toISOString()};
 if(selectedOrder)data.orderId=selectedOrder.id;else if(selectedChoice)data.orderId=selectedChoice.evidenceOrderIds[0];
 try{if(!state.demo){if(!root)throw new Error('Sign in to save your food feedback.');await api.setDoc(api.doc(root,'feedback',id),data)}state.feedback=[...state.feedback.filter(f=>f.id!==id),data];render();if(selectedOrder)openOrder(selectedOrder.id);else if(selectedChoice){const c=selectedChoice;$('#detailContent').querySelector('.feedback-options').outerHTML=feedbackForm(targetKey).match(/<div class="feedback-options">[\s\S]*?<\/div>/)[0];}toast(state.demo?'Sample reaction saved for this session.':'Your food memory has been updated.')}catch(e){toast('Could not save: '+e.message)}
}
function openSettings(){const p=result.profile,s=state.settings;$('#settingsContent').innerHTML=`<div class="connection-row"><strong>Gmail → Zomato receipts</strong><p>${state.user?`${p.orderCount} unique orders available.`:'Sign in to open your private memory.'}</p><p class="hint">${s.importSummary?`${s.importSummary.emailsRead} receipt emails checked; ${s.importSummary.duplicates} duplicate receipts removed.`:''} Last import: ${s.lastIngestedAt?date(s.lastIngestedAt):'none yet'}.</p></div><div class="connection-row"><strong>New order capture</strong><p>${s.integration?.status==='active'?'Gmail event trigger active.':state.demo?'Sample mode. No email connection.':'Event trigger setup is not yet confirmed.'}</p><p class="hint">Matching receipt emails update the same order memory through PTI. No Gmail password is stored in this app.</p></div><div class="settings-control"><label for="pauseIngestion">Pause future receipt imports</label><input type="checkbox" id="pauseIngestion" ${s.ingestionPaused?'checked':''} ${!state.user&&!state.demo?'disabled':''}></div><div class="settings-control"><label for="vegetarian">Vegetarian choices</label><input type="checkbox" id="vegetarian" ${s.vegetarian!==false?'checked':''}></div><p class="hint">Vegetarian mode excludes explicit meat/egg dish names. Unknown ingredients still need confirmation.</p><div class="dialog-actions"><button class="secondary" data-action="reload">Refresh memory</button><button class="secondary" data-action="export">Export my memory</button>${state.feedback.some(f=>f.reaction==='never')?'<button class="text-button" data-action="restore">Restore excluded meals</button>':''}</div><p class="hint">Taste data belongs to your PTI account. The app uses your explicitly chosen food mood; it does not infer emotional or mental state. Generic search links open external services; availability is checked there.</p>${state.user?'<button class="text-button" data-action="logout">Sign out of PTI</button>':''}`;$('#settingsDialog').showModal()}
async function settingsChange(key,value){try{if(state.demo){state.settings[key]=value}else{if(!root)throw new Error('Sign in to change saved preferences.');await api.setDoc(root,{[key]:value,updatedAt:new Date().toISOString()},{merge:true});state.settings[key]=value}render();toast('Preference saved.')}catch(e){toast(e.message)}}
async function login(){if(!auth){toast('Sign-in is loading. Please try again in a moment.');return}try{await api.signInWithPopup(auth,new api.GoogleAuthProvider())}catch(e){if(e.code==='auth/popup-blocked')return api.signInWithRedirect(auth,new api.GoogleAuthProvider());toast(e.message||'Sign-in did not finish.')}}
function stopListeners(){unsubs.forEach(fn=>fn());unsubs=[];sessionGeneration++}
function listen(user){stopListeners();if(!user){root=null;state={...state,user:null,orders:[],feedback:[],settings:{},loading:false,error:''};render();return}state.user=user;state.loading=true;state.error='';root=api.doc(db,'users',user.uid,'foodData','workspace');const generation=sessionGeneration;let ready=0;const receive=()=>{ready++;if(ready>=3){state.loading=false;render()}};const failure=e=>{if(generation!==sessionGeneration)return;state.loading=false;state.error=e.code==='permission-denied'?'Private food access is not active for this account.':e.message;render()};
 unsubs.push(api.onSnapshot(root,snap=>{if(generation!==sessionGeneration)return;state.settings=snap.data()||{};receive()},failure));
 unsubs.push(api.onSnapshot(api.query(api.collection(root,'orders'),api.orderBy('receivedAt','desc'),api.limit(501)),snap=>{if(generation!==sessionGeneration)return;state.orders=snap.docs.slice(0,500).map(d=>({...d.data(),id:d.id}));state.truncated=snap.size>500;receive()},failure));
 unsubs.push(api.onSnapshot(api.query(api.collection(root,'feedback'),api.orderBy('createdAt','desc'),api.limit(500)),snap=>{if(generation!==sessionGeneration)return;state.feedback=snap.docs.map(d=>({...d.data(),id:d.id}));receive()},failure));render();
}
document.addEventListener('click',async event=>{
 const b=event.target.closest('button,[data-view]');if(!b)return;
 if(b.dataset.view)return showView(b.dataset.view);
 if(b.dataset.mood){state.mood=b.dataset.mood;$('#mealStage').classList.remove('changed');void $('#mealStage').offsetWidth;$('#mealStage').classList.add('changed');render();return}
 if(b.dataset.choice!==undefined)return openChoice(b.dataset.choice);
 if(b.dataset.order)return openOrder(b.dataset.order);
 if(b.dataset.feedback)return saveFeedback(b.dataset.feedback,b.dataset.key);
 if(b.classList.contains('close-dialog'))return b.closest('dialog').close();
 const action=b.dataset.action;
 if(action==='login')return login();if(action==='settings')return openSettings();
 if(action==='reload'){if(state.demo)return toast('The sample has no cloud connection.');if(state.user)listen(state.user);else login();return}
 if(action==='logout'){stopListeners();await api.signOut(auth);$$('dialog[open]').forEach(d=>d.close());return}
 if(action==='save-note'){const key=selectedOrder?mealKey(selectedOrder):selectedChoice?.targetKey;const f=state.feedback.find(f=>f.targetKey===key);if(!f)return toast('Choose a reaction first, then save your note.');return saveFeedback(f.reaction,key)}
 if(action==='restore'){try{const excluded=state.feedback.filter(f=>f.reaction==='never');if(!state.demo){const batch=api.writeBatch(db);excluded.forEach(f=>batch.delete(api.doc(root,'feedback',f.id)));await batch.commit()}state.feedback=state.feedback.filter(f=>f.reaction!=='never');render();$('#settingsDialog').close();toast('Excluded meals restored.')}catch(e){toast(e.message)}return}
 if(action==='export'){if(!state.user&&!state.demo)return toast('Sign in to export your memory.');const blob=new Blob([JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),orders:state.orders,feedback:state.feedback,settings:state.settings},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='morsel-food-memory.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
});
$('#authButton').onclick=()=>state.user?openSettings():state.demo?toast('This sample uses fictional receipts. Sign in from the main app.'):login();$('#settingsButton').onclick=openSettings;$('#memoryStatus').onclick=()=>state.error&&state.user?listen(state.user):openSettings();
$('#hunger').onchange=e=>{state.hunger=e.target.value;render()};$('#budget').onchange=e=>{state.budget=+e.target.value;render()};$('#historySearch').oninput=()=>{historyLimit=25;renderHistory()};$('#historyStatus').onchange=()=>{historyLimit=25;renderHistory()};$('#moreHistory').onclick=()=>{historyLimit+=25;renderHistory()};
$('#settingsDialog').addEventListener('change',e=>{if(e.target.id==='pauseIngestion')settingsChange('ingestionPaused',e.target.checked);if(e.target.id==='vegetarian')settingsChange('vegetarian',e.target.checked)});
$('#motionButton').onclick=()=>{const paused=document.body.classList.toggle('motion-paused');$('#motionButton').setAttribute('aria-pressed',String(paused));$('#motionButton').setAttribute('aria-label',paused?'Resume motion':'Pause motion');$('#motionButton').textContent=paused?'▷':'Ⅱ'};
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
window.addEventListener('hashchange',()=>showView(location.hash.slice(1)));
showView(location.hash.slice(1)||'tonight');
async function boot(){
 const sample=new URLSearchParams(location.search).get('sample')==='1',qa=['localhost','127.0.0.1'].includes(location.hostname)&&globalThis.MORSEL_QA;
 if(sample||qa){const fixture=qa||await import('./sample.mjs').then(m=>m.sample);state={...state,...fixture,demo:true,user:null};render();return}
 try{
  const [app,authModule,firestore]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js')]);
  api={...authModule,...firestore};const fb=app.initializeApp({apiKey:'AIzaSyAFXtWCXQgR8Sn2H0ZWqJx_sdPM4ujO2Zs',authDomain:'pti-app-2ab59.firebaseapp.com',projectId:'pti-app-2ab59',storageBucket:'pti-app-2ab59.firebasestorage.app',messagingSenderId:'185802494856',appId:'1:185802494856:web:5e9777771492528c6e203d'});
  auth=api.getAuth(fb);db=api.initializeFirestore(fb,{localCache:api.persistentLocalCache({tabManager:api.persistentMultipleTabManager()})});api.onAuthStateChanged(auth,listen);
 }catch(e){state.error='Could not load sign-in. Check your connection and retry.';render();console.error(e)}
}
boot();if('serviceWorker'in navigator&&!['localhost','127.0.0.1'].includes(location.hostname))navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(console.warn);
