import {mealStudio, interpretCraving, interpretNote, swapMeal} from './intelligence.mjs';
import {places} from './places.mjs';
import { MOODS, FEEDBACK, entityId, mealKey } from './core.mjs';
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const moneyExact = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2,maximumFractionDigits:2}).format(value);
const date = value => new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'});
const captions = {Comfort:'Warm. Familiar. Unhurried.',Light:'A little less. Still satisfying.',Spicy:'A little fire at the table.',Indulgent:'Make room for a treat.',Familiar:'The comfort of knowing.',Explore:'A new flavour, your way.',Quick:'An easy direction to check.','Proper meal':'A plate that feels complete.'};
let state = {orders:[],feedback:[],settings:{},mood:'Comfort',hunger:'Regular',budget:0,view:'tonight',user:null,loading:false,error:'',demo:false,craving:'',diners:1,mode:'delivery',wants:[],removedWants:[],avoid:[],otherWants:[],rejectedDishIds:[],lighter:false,learning:[],preferences:[],sessions:[],memories:[],research:[]}, result, historyLimit=25, selectedChoice=null, selectedOrder=null;
let auth,db,api,root,unsubs=[],sessionGeneration=0,studio,selectedPlan=null;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function link(query,provider='zomato'){return provider==='maps'?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`:`https://www.zomato.com/search?q=${encodeURIComponent(query)}`}
function sourceUrl(order){return `https://mail.google.com/mail/u/0/#all/${order.source.gmailMessageId}`}
function showView(name){if(!['tonight','taste','history','discover'].includes(name))name='tonight';state.view=name;$$('.view').forEach(el=>el.classList.toggle('active',el.dataset.page===name));$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===name));if(location.hash!==`#${name}`)history.replaceState(null,'',`#${name}`);render();window.scrollTo({top:0,behavior:'instant'})}
function context(){return {craving:state.craving,mood:state.mood,hunger:state.hunger,budget:state.budget,diners:state.diners,mode:state.mode,wants:state.wants,removedWants:state.removedWants,avoid:state.avoid,otherWants:state.otherWants,rejectedDishIds:state.rejectedDishIds,lighter:state.lighter,proactive:state.settings.proactive===true,vegetarian:state.settings.vegetarian!==false}}
function render(){
 studio=mealStudio({...state,research:state.demo?state.research:[...places,...state.research],context:context()});result={...studio,choices:studio.plans};
 $('#moods').innerHTML=MOODS.map(m=>`<button class="mood-chip ${state.mood===m?'active':''}" data-mood="${esc(m)}" aria-pressed="${state.mood===m}">${esc(m)}</button>`).join('');
 $('#moodWord').textContent=state.mood;$('#moodCaption').textContent=captions[state.mood];$('#mealStage').dataset.mood=state.mood;
 $('#authButton').textContent=state.demo?'Sample mode':state.user?(state.user.displayName?.split(' ')[0]||'Account'):'Sign in';
 const hour=Number(new Intl.DateTimeFormat('en-GB',{hour:'numeric',hourCycle:'h23',timeZone:'Asia/Kolkata'}).format(new Date()));
 $('#greeting').textContent=state.demo?'Sample table · fictional food memory':`${hour<12?'Good morning':hour<17?'Good afternoon':'Good evening'}${state.user?.displayName?', '+state.user.displayName.split(' ')[0]:''}. Let’s set your table.`;
 $('#memoryStatus').classList.toggle('sync-error',!!state.error);
 $('#memoryStatus').textContent=state.error?'Sync failed · retry':state.loading?'Opening your memory…':state.demo?'Sample · no cloud writes':state.user?`${studio.profile.orderCount} orders · ${studio.taste.confirmedMeals} meals with feedback`:'Connect your food memory';
 $('#choiceHeading').textContent=state.craving?'A table shaped around you.':'A familiar yes. A little surprise.';
 $('#choiceMeta').textContent=state.user||state.demo?`${studio.intent.diners} diner${studio.intent.diners>1?'s':''} · ${studio.intent.mode}`:'Your history is the starting point';
 $('#groupContext').hidden=state.diners<2;
 $('#intentSummary').innerHTML=`<div class="intent-cues">${studio.intent.understood.map(t=>`<span>${esc(t)}</span>`).join('')}</div><details class="cue-refinements" ${matchMedia('(min-width:701px)').matches?'open':''}><summary>Adjust food cues</summary><p>${esc(studio.intent.interpretation)}</p><div class="cue-editor">${['smoky','crispy','tangy','soft','lighter'].map(t=>`<button data-cue="${t}" class="${studio.intent.wants.includes(t)?'active':''}" aria-pressed="${studio.intent.wants.includes(t)}">${t}</button>`).join('')}<button data-refine="lighter">Less rich today</button>${state.rejectedDishIds.length||state.avoid.length||state.lighter?'<button data-reset="1">Reset today’s refinements</button>':''}</div></details>${studio.intent.question?`<div class="one-question"><strong>${esc(studio.intent.question.text)}</strong>${studio.intent.question.options.map(o=>`<button data-cue="${o.signal}">${esc(o.label)}</button>`).join('')}</div>`:''}`;
 $('#intelligenceCue').innerHTML=(state.user||state.demo)?studio.insights.map(c=>`<div><strong>${esc(c.title)}</strong><p>${esc(c.text)}</p>${c.orderId?`<button data-order="${esc(c.orderId)}">Open this meal</button>`:''}</div>`).join(''):'';
 renderChoices();renderMemory();renderSessions();if(state.view==='taste')renderTaste();if(state.view==='history')renderHistory();if(state.view==='discover')renderDiscover();
}
function empty(title,copy,button=''){return `<div class="empty-panel"><div><h3>${title}</h3><p>${copy}</p></div>${button}</div>`}
const modeNames={familiar:'A familiar yes',twist:'One deliberate twist',explore:'A new direction'};
function renderChoices(){
 const el=$('#choices');
 if(state.loading&&!state.orders.length){el.innerHTML=empty('Setting your table…','Opening your private food memory.');return}
 if(!state.user&&!state.demo){el.innerHTML=empty('A table that becomes yours.','Open your history, shape a meal and discover what works for you.','<button class="primary" data-action="login">Open my food studio</button>');return}
 if(state.error&&!state.orders.length){el.innerHTML=empty('Your memory could not be opened.',esc(state.error),'<button class="primary" data-action="reload">Try again</button>');return}
 if(!studio.plans.length){el.innerHTML=empty('Let’s change one cue.',esc(studio.note),'<button class="secondary" data-reset="1">Reset today’s refinements</button>');return}
 el.innerHTML=studio.plans.map((c,i)=>`<article class="choice"><div class="choice-top"><span class="mode">${esc(modeNames[c.mode])}</span><span class="choice-number">0${i+1}</span></div><div class="meal-slots">${c.items.map(x=>`<span class="meal-slot ${x.slot}"><small>${esc(x.slot)}</small><strong>${esc(x.name)}</strong></span>`).join('')}</div><p class="restaurant">${esc(c.restaurant)}</p><p class="why">${esc(c.reasons[0]||'A direction to explore.')}</p>${c.experiment?`<p class="experiment">${esc(c.experiment.keep.length?'Keep '+c.experiment.keep.join(' + ')+'. Change the main.':'Try one new dish. Learn what worked.')}</p>`:''}<div class="choice-bottom"><span class="price">${c.total!==null?money(c.total)+' listed items':'Price needs checking'}</span><button data-plan="${i}">Shape this meal →</button></div><button class="not-today" data-reject="${i}">Not today</button></article>`).join('')+`<p class="choice-note">${esc(studio.note)} Budget applies to known item prices; unpriced directions need a menu check. Quantities are chosen after checking portions.</p>`;
}
function renderMemory(){
 const p=result.profile;
 $('#memoryStrip').innerHTML=[[''+p.orderCount,'unique orders'],[''+p.restaurants.length,'restaurants'],[''+p.dishes.length,'dishes remembered']].map(([n,label])=>`<div class="memory-stat"><strong>${n}</strong><span>${label}</span></div>`).join('');
 const last=[...state.orders].sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt))[0];
 $('#lastMeal').innerHTML=last?`<p class="eyebrow">LAST AT YOUR TABLE</p><button data-order="${esc(last.id)}">${esc(last.restaurantName)}</button><span>${date(last.receivedAt)} · ${esc(last.items.slice(0,2).map(x=>x.name).join(' + '))}</span>`:'<p class="eyebrow">A MEMORY THAT GROWS</p><p>Each receipt becomes a little more context.</p>';
}
function bars(items,total){return items.slice(0,7).map(x=>`<div class="bar-row"><span>${esc(x.name)}</span><div class="bar-track" aria-hidden="true"><div class="bar-fill" style="width:${Math.max(2,x.count/Math.max(1,total)*100)}%"></div></div><strong>${x.count}</strong></div>`).join('')}
function renderTaste(){
 const p=result.profile;if(!p.orderCount){$('#tasteContent').innerHTML=tasteIntelligence()+empty('Your taste is still taking shape.','Open your food memory to see the dishes, cuisines and places you return to.');return}
 $('#tasteContent').innerHTML=tasteIntelligence()+`<details class="receipt-evidence"><summary>Patterns in your receipts</summary><div class="taste-grid"><div><section class="taste-section"><h2>Where your taste leans</h2>${bars(p.cuisines,p.orderCount)}<p class="taste-note">Counts are orders containing each cuisine. A mixed meal can appear in more than one cuisine. Labels are inferred from dish names.</p></section><section class="taste-section"><h2>The dishes you return to</h2>${p.dishes.slice(0,10).map(d=>`<div class="food-rank"><div>${esc(d.name)}<span>${esc(d.cuisine)} · last ${date(d.lastAt)}</span></div><strong>${d.count} orders</strong></div>`).join('')}</section></div><div><section class="taste-section"><h2>A hint of your flavour palette</h2>${bars(p.tags,p.orderCount)}<p class="taste-note">These are name-based hints, not tasted flavours or measured ingredient preferences.</p></section><section class="taste-section"><h2>Your familiar tables</h2>${p.restaurants.slice(0,6).map(r=>`<div class="food-rank"><div>${esc(r.name)}<span>${money(r.averagePaid)} average past basket</span></div><strong>${r.count} orders</strong></div>`).join('')}</section><div class="feedback-teaser"><h3>Receipts tell only half the story.</h3><p class="hint">You have left ${state.feedback.length} meal reactions. Loved, good, okay or “don’t suggest again” helps turn repeats into preferences.</p><button class="text-button" data-view="history">Add a little meaning</button></div></div></div><p class="taste-note">${date(p.firstAt)} to ${date(p.lastAt)} · ${money(p.totalPaid)} in imported delivered receipts. Some baskets were shared; this is order history, not individual intake. Time patterns use receipt timestamps in India.</p></details>`;
}
function renderHistory(){
 const needle=$('#historySearch').value.toLowerCase().trim(),status=$('#historyStatus').value;
 const rows=[...state.orders].filter(o=>(status==='all'||o.status===status)&&(!needle||[o.restaurantName,...o.items.map(i=>i.name)].join(' ').toLowerCase().includes(needle))).sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt));
 let month='';$('#historyList').innerHTML=rows.slice(0,historyLimit).map(o=>{
  const m=new Date(o.receivedAt).toLocaleDateString('en-IN',{month:'long',year:'numeric',timeZone:'Asia/Kolkata'}),head=m!==month?`<h2 class="history-month">${m}</h2>`:'';month=m;
  const time=new Intl.DateTimeFormat('en-IN',{day:'2-digit',weekday:'short',timeZone:'Asia/Kolkata'}).formatToParts(new Date(o.receivedAt)), day=time.find(x=>x.type==='day').value,weekday=time.find(x=>x.type==='weekday').value;
  const f=state.feedback.find(f=>f.targetKey===mealKey(o));
  return `${head}<button class="order-row" data-order="${esc(o.id)}"><span class="order-date"><strong>${day}</strong>${weekday}</span><div><h3>${esc(o.restaurantName)}</h3><p>${esc(o.items.map(x=>`${x.quantity} × ${x.name}`).join(' · '))}</p></div><span class="order-cost">${money(o.total)}<span>${f?esc(f.reaction==='never'?'Excluded':f.reaction):esc(o.status)}</span></span></button>`;
 }).join('')||empty('No meals here yet.',needle?'Try a different dish or restaurant.':'Your imported receipts will appear here.');
 $('#moreHistory').hidden=rows.length<=historyLimit;
}
function renderDiscover(){
 const catalogue=state.demo?state.research:[...places,...state.research];
 $('#discoveryList').innerHTML=`<p class="discovery-intro">Discovery starts with a bridge: keep a quality you like, then change a dish or preparation. Your current cues also apply here.</p>`+catalogue.map((v,i)=>`<article class="discovery-card"><span class="discovery-number">0${i+1}</span><div><h2>${esc(v.name)}</h2><p>${esc(v.outlet||'')}</p><div class="discovery-dishes">${v.items.map(d=>`<button data-discover="${esc(d.name)}">${esc(d.name)}</button>`).join('')}</div></div><p class="discovery-basis">Menu retrieved ${date(v.checkedAt)}<br>${esc(v.note||'Current availability and prices need checking.')}</p><a class="secondary" target="_blank" rel="noopener noreferrer" href="${esc(safeUrl(v.url))}">Inspect menu ↗</a></article>`).join('')+'<p class="taste-note">Listings age after 14 days. Restaurant research can be updated through the shared food tools. Prices and delivery availability are checked in the ordering service.</p>';
}
function safeUrl(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:'#'}catch{return '#'}}
function feedbackForm(targetKey){const f=state.feedback.find(x=>x.targetKey===targetKey);return `<h3>How does this meal feel to you?</h3><div class="feedback-options">${[['loved','Loved'],['good','Good'],['okay','Okay'],['never','Don’t suggest again']].map(([value,label])=>`<button data-feedback="${value}" data-key="${esc(targetKey)}" class="${f?.reaction===value?'active':''}" aria-pressed="${f?.reaction===value}">${label}</button>`).join('')}</div><label class="feedback-note">A note, if you like<input id="feedbackNote" maxlength="1000" value="${esc(f?.note||'')}" placeholder="Too rich, loved the spice, want this again…"></label><button class="text-button" data-action="save-note">Save note</button><p class="hint">Your chosen food mood: ${esc(state.mood)}. Reactions are saved to your private memory.</p>`}
function openOrder(id){const order=state.orders.find(o=>o.id===id);if(!order)return;selectedOrder=order;selectedChoice=null;selectedPlan=null;const f=state.feedback.find(x=>x.targetKey===mealKey(order));$('#detailContent').innerHTML=`<p class="eyebrow">ZOMATO RECEIPT · ${esc(order.orderId)}</p><h2>${esc(order.restaurantName)}</h2><p>${date(order.receivedAt)} · ${esc(order.status)}</p><p class="hint">${esc(order.outlet)}</p><div class="detail-items">${order.items.map(i=>`<div class="detail-item"><span>${esc(i.name)}</span><strong>× ${i.quantity}</strong></div>`).join('')}</div><div class="detail-total"><span>Total paid</span><span>${moneyExact(order.total)}</span></div><p class="hint">Full basket total; quantities may include other diners. Original dish wording is retained in the source record.</p>${order.status==='delivered'?dishLearningForm(order):'<p class="hint">Cancelled receipts do not teach personal enjoyment.</p>'}<details><summary>Whole basket feedback</summary>${feedbackForm(mealKey(order))}</details>${memoryForm(order)}<a class="source-link" href="${sourceUrl(order)}" target="_blank" rel="noopener noreferrer">Open original email</a>`;if(!$('#detailDialog').open)$('#detailDialog').showModal()}
async function saveFeedback(reaction,targetKey){
 if(!FEEDBACK.includes(reaction))return;
 const note=$('#feedbackNote')?.value||'', id=entityId(targetKey),existing=state.feedback.find(f=>f.targetKey===targetKey),data={id,targetKey,reaction,note,mood:state.mood,createdAt:new Date().toISOString()};
 if(selectedOrder)data.orderId=selectedOrder.id;else if(selectedChoice)data.orderId=selectedChoice.evidenceOrderIds[0];
 try{if(!state.demo){if(!root)throw new Error('Sign in to save your food feedback.');await api.setDoc(api.doc(root,'feedback',id),data)}state.feedback=[...state.feedback.filter(f=>f.id!==id),data];render();if(selectedOrder)openOrder(selectedOrder.id);else if(selectedChoice){const c=selectedChoice;$('#detailContent').querySelector('.feedback-options').outerHTML=feedbackForm(targetKey).match(/<div class="feedback-options">[\s\S]*?<\/div>/)[0];}toast(state.demo?'Sample reaction saved for this session.':'Your food memory has been updated.')}catch(e){toast('Could not save: '+e.message)}
}
function openSettings(){const p=result.profile,s=state.settings;$('#settingsContent').innerHTML=`<div class="connection-row"><strong>Gmail → Zomato receipts</strong><p>${state.user?`${p.orderCount} unique orders available.`:'Sign in to open your private memory.'}</p><p class="hint">${s.importSummary?`${s.importSummary.emailsRead} receipt emails checked; ${s.importSummary.duplicates} duplicate receipts removed.`:''} Last import: ${s.lastIngestedAt?date(s.lastIngestedAt):'none yet'}.</p></div><div class="connection-row"><strong>New order capture</strong><p>${s.integration?.status==='active'?'Gmail event trigger active.':state.demo?'Sample mode. No email connection.':'Event trigger setup is not yet confirmed.'}</p><p class="hint">Matching receipt emails update the same order memory through PTI. No Gmail password is stored in this app.</p></div><div class="settings-control"><label for="pauseIngestion">Pause future receipt imports</label><input type="checkbox" id="pauseIngestion" ${s.ingestionPaused?'checked':''} ${!state.user&&!state.demo?'disabled':''}></div><div class="settings-control"><label for="vegetarian">Vegetarian choices</label><input type="checkbox" id="vegetarian" ${s.vegetarian!==false?'checked':''}></div><p class="hint">Vegetarian mode excludes explicit meat/egg dish names. Unknown ingredients still need confirmation.</p><div class="dialog-actions"><button class="secondary" data-action="reload">Refresh memory</button><button class="secondary" data-action="export">Export my memory</button>${state.feedback.some(f=>f.reaction==='never')?'<button class="text-button" data-action="restore">Restore excluded meals</button>':''}</div><p class="hint">Taste data belongs to your PTI account. The app uses your explicitly chosen food mood; it does not infer emotional or mental state. Generic search links open external services; availability is checked there.</p><div class="settings-control"><label for="proactive">Show helpful cues when I open my table</label><input type="checkbox" id="proactive" ${s.proactive?'checked':''}></div>${state.user?'<button class="text-button" data-action="logout">Sign out of PTI</button>':''}`;$('#settingsDialog').showModal()}
async function settingsChange(key,value){try{if(state.demo){state.settings[key]=value}else{if(!root)throw new Error('Sign in to change saved preferences.');await api.setDoc(root,{[key]:value,updatedAt:new Date().toISOString()},{merge:true});state.settings[key]=value}render();toast('Preference saved.')}catch(e){toast(e.message)}}
async function login(){if(!auth){toast('Sign-in is loading. Please try again in a moment.');return}try{await api.signInWithPopup(auth,new api.GoogleAuthProvider())}catch(e){if(e.code==='auth/popup-blocked')return api.signInWithRedirect(auth,new api.GoogleAuthProvider());toast(e.message||'Sign-in did not finish.')}}
function stopListeners(){unsubs.forEach(fn=>fn());unsubs=[];sessionGeneration++}
function listen(user){
 stopListeners();if(!user){root=null;state={...state,user:null,orders:[],feedback:[],settings:{},learning:[],preferences:[],sessions:[],memories:[],research:[],loading:false,error:''};render();return}
 state.user=user;state.loading=true;state.error='';root=api.doc(db,'users',user.uid,'foodData','workspace');const generation=sessionGeneration,ready=new Set();
 const failure=e=>{if(generation!==sessionGeneration)return;state.loading=false;state.error=e.code==='permission-denied'?'Private food access is not active for this account.':e.message;render()};
 const receive=(key,data)=>{if(generation!==sessionGeneration)return;state[key]=data;ready.add(key);state.loading=ready.size<8;render()};
 unsubs.push(api.onSnapshot(root,snap=>receive('settings',snap.data()||{}),failure));
 for(const[name,field]of [['orders','receivedAt'],['feedback','createdAt'],['learning','createdAt'],['preferences','createdAt'],['sessions','createdAt'],['memories','createdAt'],['research','checkedAt']]){
  unsubs.push(api.onSnapshot(api.query(api.collection(root,name),api.orderBy(field,'desc'),api.limit(name==='orders'?501:300)),snap=>{if(name==='orders')state.truncated=snap.size>500;receive(name,snap.docs.slice(0,name==='orders'?500:300).map(d=>({...d.data(),id:d.id})))},failure));
 }
 render();
}
document.addEventListener('click',async event=>{
 const b=event.target.closest('button,[data-view]');if(!b)return;
 if(b.dataset.view)return showView(b.dataset.view);
 if(await studioAction(b))return;
 if(b.dataset.mood){state.mood=b.dataset.mood;$('#mealStage').classList.remove('changed');void $('#mealStage').offsetWidth;$('#mealStage').classList.add('changed');render();return}
 if(b.dataset.order)return openOrder(b.dataset.order);
 if(b.dataset.feedback)return saveFeedback(b.dataset.feedback,b.dataset.key);
 if(b.classList.contains('close-dialog'))return b.closest('dialog').close();
 const action=b.dataset.action;
 if(action==='login')return login();if(action==='settings')return openSettings();
 if(action==='reload'){if(state.demo)return toast('The sample has no cloud connection.');if(state.user)listen(state.user);else login();return}
 if(action==='logout'){stopListeners();await api.signOut(auth);$$('dialog[open]').forEach(d=>d.close());return}
 if(action==='save-note'){const key=selectedOrder?mealKey(selectedOrder):selectedChoice?.targetKey;const f=state.feedback.find(f=>f.targetKey===key);if(!f)return toast('Choose a reaction first, then save your note.');return saveFeedback(f.reaction,key)}
 if(action==='restore'){try{const excluded=state.feedback.filter(f=>f.reaction==='never');if(!state.demo){const batch=api.writeBatch(db);excluded.forEach(f=>batch.delete(api.doc(root,'feedback',f.id)));await batch.commit()}state.feedback=state.feedback.filter(f=>f.reaction!=='never');render();$('#settingsDialog').close();toast('Excluded meals restored.')}catch(e){toast(e.message)}return}
 if(action==='export'){if(!state.user&&!state.demo)return toast('Sign in to export your memory.');const blob=new Blob([JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),orders:state.orders,feedback:state.feedback,learning:state.learning,preferences:state.preferences,sessions:state.sessions,memories:state.memories,research:state.research,settings:state.settings},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='morsel-food-memory.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
});
$('#authButton').onclick=()=>state.user?openSettings():state.demo?toast('This sample uses fictional receipts. Sign in from the main app.'):login();$('#settingsButton').onclick=openSettings;$('#memoryStatus').onclick=()=>state.error&&state.user?listen(state.user):openSettings();
$('#hunger').onchange=e=>{state.hunger=e.target.value;render()};$('#budget').onchange=e=>{state.budget=+e.target.value;render()};$('#historySearch').oninput=()=>{historyLimit=25;renderHistory()};$('#historyStatus').onchange=()=>{historyLimit=25;renderHistory()};$('#moreHistory').onclick=()=>{historyLimit+=25;renderHistory()};
$('#settingsDialog').addEventListener('change',e=>{if(e.target.id==='pauseIngestion')settingsChange('ingestionPaused',e.target.checked);if(e.target.id==='vegetarian')settingsChange('vegetarian',e.target.checked);if(e.target.id==='proactive')settingsChange('proactive',e.target.checked)});
$('#motionButton').onclick=()=>{const paused=document.body.classList.toggle('motion-paused');$('#motionButton').setAttribute('aria-pressed',String(paused));$('#motionButton').setAttribute('aria-label',paused?'Resume motion':'Pause motion');$('#motionButton').textContent=paused?'▷':'Ⅱ'};
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
window.addEventListener('hashchange',()=>showView(location.hash.slice(1)));
showView(location.hash.slice(1)||'tonight');
async function boot(){
 const sample=new URLSearchParams(location.search).get('sample')==='1',qa=['localhost','127.0.0.1'].includes(location.hostname)&&globalThis.MORSEL_QA;
 if(sample||qa){const fixture=qa||await import('./sample.mjs').then(m=>m.sample);state={...state,...fixture,demo:true,user:null};render();return}
 try{
  const [app,authModule,firestore]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js')]);
  api={...authModule,...firestore};const fb=app.initializeApp({apiKey:'AIzaSyAFXtWCXQgR8Sn2H0ZWqJx_sdPM4ujO2Zs',authDomain:'pti-app-2ab59.firebaseapp.com',projectId:'pti-app-2ab59',storageBucket:'pti-app-2ab59.firebasestorage.app',messagingSenderId:'185802494856',appId:'1:185802494856:web:5e9777771492528c6e203d'});
  auth=api.getAuth(fb);db=api.initializeFirestore(fb,{localCache:api.persistentLocalCache({tabManager:api.persistentMultipleTabManager()})});api.onAuthStateChanged(auth,listen);
 }catch(e){state.error='Could not load sign-in. Check your connection and retry.';render();console.error(e)}
}
installStudioEvents();
boot();if('serviceWorker'in navigator&&!['localhost','127.0.0.1'].includes(location.hostname))navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(console.warn);

function tasteIntelligence(){
 const t=studio.taste;
 const question=t.questions[0];
 return `<section class="taste-intelligence"><div><p class="eyebrow">A TASTE YOU CAN SHAPE</p><h2>${t.confirmedMeals} ${t.confirmedMeals===1?'meal':'meals'} with your own feedback.</h2><p>Repeated orders suggest possibilities. Your confirmed preferences and dish reactions give them meaning.</p></div><div class="preference-grid">${t.observations.map(p=>`<div class="preference-row"><div><strong>${esc(p.signal)}</strong><small>${esc(p.basis)}</small></div><div class="stance-options">${[['like','Enjoy'],['neutral','Open'],['avoid','Avoid']].map(([v,label])=>`<button data-preference="${p.signal}" data-stance="${v}" class="${p.stance===v?'active':''}" aria-pressed="${p.stance===v}">${label}</button>`).join('')}</div></div>`).join('')}</div>${state.preferences.some(p=>p.scope!=='always')?`<div class="context-preferences"><h3>What fits a particular food mood</h3>${state.preferences.filter(p=>p.scope!=='always').map(p=>`<div class="preference-row"><div><strong>${esc(p.signal)}</strong><small>For ${esc(p.scope)} · you confirmed this</small></div><div class="stance-options">${[['like','Enjoy'],['neutral','Open'],['avoid','Avoid']].map(([v,label])=>`<button data-preference="${p.signal}" data-scope="${p.scope}" data-stance="${v}" class="${p.stance===v?'active':''}" aria-pressed="${p.stance===v}">${label}</button>`).join('')}</div></div>`).join('')}</div>`:''}${question?`<div class="learning-question"><strong>${esc(question.text)}</strong><p>Confirm a lasting preference, or leave the question open.</p><button data-preference="${question.signal}" data-stance="like">Yes, I enjoy it</button><button data-preference="${question.signal}" data-stance="neutral">It depends</button></div>`:''}<div class="confirmed-evidence">${t.evidence.slice(0,4).map(e=>`<p><strong>${esc(e.name)}</strong> · ${esc(e.reaction)} · ${esc(e.mood)} ${e.reason==='convenience'?'· also chosen for convenience':''}</p>`).join('')}</div></section><section class="food-memories"><p class="eyebrow">YOUR LITTLE RITUALS</p><h2>More than a receipt.</h2>${state.memories.length?state.memories.map(m=>`<article><button data-order="${esc(m.orderId)}"><strong>${esc(m.title)}</strong></button><span>${esc(m.occasion)}</span><p>${esc(m.note)}</p><button data-delete-memory="${esc(m.id)}">Remove memory</button></article>`).join(''):'<p>Open a meal in History and save what made it worth remembering—a weekend ritual, an outing, a meal you want to recreate.</p><button data-view="history" class="secondary">Find a meal to remember</button>'}</section>`;
}
function renderSessions(){
 const active=state.sessions.filter(s=>['chosen','receipt-linked'].includes(s.status)).slice(0,3);
 $('#chosenMeals').innerHTML=active.length?`<p class="eyebrow">SET ASIDE FOR YOU</p>${active.map(s=>`<div class="chosen-row"><div><strong>${esc(s.restaurant)}</strong><p>${esc(s.itemNames.join(' + '))}</p><small>${s.status==='receipt-linked'?'A receipt matches this plan. Which dishes did you eat?':'A chosen direction; placing an order happens in Zomato.'}</small></div>${s.linkedOrderId?`<button data-order="${esc(s.linkedOrderId)}">Add dish feedback</button>`:`<button data-cancel-session="${esc(s.id)}">Clear plan</button>`}</div>`).join('')}`:'';
}
function openPlan(index){
 selectedPlan=structuredClone(studio.plans[+index]);selectedOrder=null;selectedChoice=null;if(!selectedPlan)return;renderPlan();if(!$('#detailDialog').open)$('#detailDialog').showModal();
}
function renderPlan(){
 const c=selectedPlan;if(!c)return;
 const anchors=studio.candidates.filter(d=>d.restaurantId===c.restaurantId&&!['accompaniment','finish'].includes(d.knowledge.role));
 const extras=studio.candidates.filter(d=>d.restaurantId===c.restaurantId&&!c.items.some(i=>i.id===d.id)&&d.knowledge.role!=='main');
 $('#detailContent').innerHTML=`<p class="eyebrow">${esc(modeNames[c.mode])} · YOUR MEAL STUDIO</p><h2>Make this table yours.</h2><p>${esc(c.restaurant)} · ${esc(c.outlet)}</p><div class="composition">${c.items.map((i,n)=>`<div class="composition-piece"><small>${esc(i.slot)}</small><strong>${esc(i.name)}</strong><span>${esc(i.knowledge.signals.slice(0,3).join(' · '))}</span>${n?`<button data-remove-piece="${n}" aria-label="Remove ${esc(i.name)}">Remove</button>`:''}</div>`).join('')}</div><label class="studio-field">Change the anchor<select id="swapAnchor">${anchors.map(d=>`<option value="${esc(d.id)}" ${d.id===c.items[0].id?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label>${extras.length?`<label class="studio-field">Add a contrast or accompaniment<select id="extraDish"><option value="">Choose one, if it belongs…</option>${extras.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label>`:''}<h3>Why this direction</h3><ul>${c.reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul>${c.experiment?`<div class="experiment-detail"><strong>One thing to learn</strong><p>${esc(c.experiment.question)}</p><p>${esc(c.experiment.keep.length?'Keep '+c.experiment.keep.join(' + ')+', change the format.':'A new dish with some familiar food qualities.')}</p></div>`:''}<h3>Before you choose</h3><ul class="tradeoffs">${c.tradeoffs.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><p class="hint">${c.checkedAt?'Menu listing retrieved '+date(c.checkedAt):'Receipt evidence; the current menu has not been checked.'} ${c.total!==null?'Listed items '+money(c.total)+', before extras.':''}</p><div class="dialog-actions"><button class="primary" data-choose-plan="1">This is my direction</button><a class="secondary" href="${esc((c.sourceUrl?safeUrl(c.sourceUrl):'')||link(c.restaurant+' Kharghar'))}" target="_blank" rel="noopener noreferrer">${c.checkedAt?'Inspect menu':'Open evidence'} ↗</a><a class="text-button" href="${link(c.restaurant+' '+c.outlet+(c.outlet?'':' Kharghar'),studio.intent.mode==='dine-in'?'maps':'zomato')}" target="_blank" rel="noopener noreferrer">${studio.intent.mode==='dine-in'?'Find on Maps':'Find in Zomato'}</a></div>`;
}
function dishLearningForm(order){
 const linked=state.sessions.find(s=>s.linkedOrderId===order.id),mealMood=state.learning.find(l=>l.orderId===order.id)?.mood||linked?.context?.mood||state.mood;
 return `<section class="dish-learning">${linked?`<div class="experiment-detail"><strong>A direction you chose</strong><p>${esc(linked.itemNames.join(' + '))}</p>${linked.experiment?`<p>${esc(linked.experiment.question)}</p>`:''}</div>`:''}<h3>Which dishes were yours?</h3><p class="hint">Mark only what you ate. A shared basket is not an individual preference.</p><label class="studio-field">The food mood for this meal<select id="reactionMood">${MOODS.map(m=>`<option ${m===mealMood?'selected':''}>${m}</option>`).join('')}</select></label>${order.items.map(i=>{const l=state.learning.find(l=>l.orderId===order.id&&l.dishId===i.dishId);return `<div class="dish-reaction" data-dish-row="${esc(i.dishId)}"><strong>${esc(i.name)}</strong><label><input type="checkbox" data-eaten="${esc(i.dishId)}" ${l?.eaten?'checked':''}> I ate this</label><div class="dish-buttons">${[['loved','Loved'],['good','Good'],['okay','Okay'],['never','Avoid this dish']].map(([r,label])=>`<button data-dish-reaction="${r}" data-dish="${esc(i.dishId)}" class="${l?.reaction===r?'active':''}" aria-pressed="${l?.reaction===r}">${label}</button>`).join('')}</div><label class="studio-field">Why it was chosen<select data-repeat-reason="${esc(i.dishId)}"><option value="taste" ${l?.reason==='taste'?'selected':''}>I wanted this food</option><option value="convenience" ${l?.reason==='convenience'?'selected':''}>Convenience also mattered</option><option value="other" ${l?.reason==='other'?'selected':''}>For someone else</option></select></label><label class="studio-field">A note<input maxlength="1000" data-dish-note="${esc(i.dishId)}" value="${esc(l?.note||'')}" placeholder="Loved the spice, too rich…"></label>${l?.note&&interpretNote(l.note).length?`<div class="note-confirm"><p>I found possible preferences in your note. Confirm only the ones you mean.</p>${interpretNote(l.note).map(h=>`<button data-note-signal="${h.signal}" data-stance="${h.stance}" data-scope="${l.mood}">${esc(h.stance==='like'?'Enjoy':'Avoid')} ${esc(h.signal)} for ${esc(l.mood)}</button>`).join('')}</div>`:''}<button class="text-button" data-save-dish="${esc(i.dishId)}">Save this dish feedback</button></div>`}).join('')}</section>`;
}
function memoryForm(order){
 const m=state.memories.find(m=>m.orderId===order.id);
 return `<details class="memory-form"><summary>Remember what made this meal special</summary><label class="studio-field">Name this memory<input id="memoryTitle" maxlength="120" placeholder="Our slow Sunday lunch" value="${esc(m?.title||'')}"></label><label class="studio-field">Occasion<select id="memoryOccasion"><option value="any">A meal to revisit</option><option value="weekend" ${m?.occasion==='weekend'?'selected':''}>Weekend ritual</option><option value="outing" ${m?.occasion==='outing'?'selected':''}>An outing</option><option value="celebration" ${m?.occasion==='celebration'?'selected':''}>A celebration</option></select></label><label class="studio-field">What would you like to remember?<input id="memoryNote" maxlength="1000" value="${esc(m?.note||'')}" placeholder="The meal, the company, something to recreate…"></label><button class="secondary" data-save-memory="${esc(order.id)}">Save this memory</button></details>`;
}
async function putPrivate(collectionName,data,id){
 if(!state.user&&!state.demo)throw new Error('Sign in to save to your food memory.');
 const record={...data,id,createdAt:data.createdAt||new Date().toISOString()};
 if(!state.demo)await api.setDoc(api.doc(root,collectionName,id),record);
 state[collectionName]=[record,...state[collectionName].filter(x=>x.id!==id)];render();return record;
}
async function saveDish(dishId,reaction){
 if(!selectedOrder)return;const order=selectedOrder,item=order.items.find(i=>i.dishId===dishId);if(!item)return;
 const row=$(`[data-dish-row="${dishId}"]`),existing=state.learning.find(l=>l.orderId===order.id&&l.dishId===dishId);
 const eaten=row.querySelector('[data-eaten]').checked,reason=row.querySelector('[data-repeat-reason]').value;
 const chosenReaction=reaction||existing?.reaction||'okay';
 await putPrivate('learning',{orderId:order.id,dishId,restaurantId:order.restaurantId,eaten,reaction:chosenReaction,reason,note:row.querySelector('[data-dish-note]').value,mood:$('#reactionMood').value},entityId(order.id+'__'+dishId));
 openOrder(order.id);toast(eaten&&reason!=='other'?'Your dish feedback will shape future meals.':'Saved without treating this dish as your enjoyment.');
}
async function studioAction(b){
 try{
 if(b.dataset.plan!==undefined){openPlan(b.dataset.plan);return true}
 if(b.dataset.cue){const cue=b.dataset.cue;if(studio.intent.wants.includes(cue)){state.wants=state.wants.filter(x=>x!==cue);state.removedWants=[...new Set([...state.removedWants,cue])]}else{state.wants=[...new Set([...state.wants,cue])];state.removedWants=state.removedWants.filter(x=>x!==cue)}state.avoid=state.avoid.filter(x=>x!==cue);render();return true}
 if(b.dataset.reset){state.wants=[];state.removedWants=[];state.avoid=[];state.rejectedDishIds=[];state.lighter=false;state.craving='';$('#craving').value='';render();return true}
 if(b.dataset.refine){state.lighter=true;state.avoid=[...new Set([...state.avoid,'rich'])];render();return true}
 if(b.dataset.reject!==undefined){const c=studio.plans[+b.dataset.reject];if(c){state.rejectedDishIds=[...new Set([...state.rejectedDishIds,...c.items.map(i=>i.dishId)])];render();toast('Changed for today. Lasting preferences are unchanged.')}return true}
 if(b.dataset.choosePlan){if(!selectedPlan)return true;const c=selectedPlan;await putPrivate('sessions',{restaurantId:c.restaurantId,restaurant:c.restaurant,dishIds:c.items.map(i=>i.dishId),itemNames:c.items.map(i=>i.name),status:'chosen',context:{craving:state.craving,mood:studio.intent.mood,wants:studio.intent.wants,avoid:studio.intent.avoid,diners:studio.intent.diners,budget:studio.intent.budget,mode:studio.intent.mode},experiment:c.experiment||null},'meal-'+crypto.randomUUID());$('#detailDialog').close();toast('Your direction is saved. Place the order in Zomato.');return true}
 if(b.dataset.removePiece){if(selectedPlan){selectedPlan.items.splice(+b.dataset.removePiece,1);selectedPlan.targetKey=`${selectedPlan.restaurantId}__${selectedPlan.items.map(i=>i.dishId).sort().join('_')}`;selectedPlan.total=selectedPlan.items.every(i=>i.price!==null&&i.listed)?selectedPlan.items.reduce((n,i)=>n+i.price,0):null;renderPlan()}return true}
 if(b.dataset.dishReaction){await saveDish(b.dataset.dish,b.dataset.dishReaction);return true}
 if(b.dataset.saveDish){await saveDish(b.dataset.saveDish);return true}
 if(b.dataset.preference||b.dataset.noteSignal){const signal=b.dataset.preference||b.dataset.noteSignal,scope=b.dataset.scope||(b.dataset.noteSignal?$('#reactionMood')?.value||state.mood:'always');await putPrivate('preferences',{signal,stance:b.dataset.stance,scope},entityId(scope+'__'+signal));toast('Confirmed preference saved.');return true}
 if(b.dataset.saveMemory){const title=$('#memoryTitle').value.trim();if(!title){toast('Give this memory a name.');return true}await putPrivate('memories',{orderId:b.dataset.saveMemory,title,note:$('#memoryNote').value.trim(),occasion:$('#memoryOccasion').value},entityId('memory__'+b.dataset.saveMemory));$('#detailDialog').close();toast('A meal worth remembering.');return true}
 if(b.dataset.deleteMemory){if(!state.demo)await api.deleteDoc(api.doc(root,'memories',b.dataset.deleteMemory));state.memories=state.memories.filter(m=>m.id!==b.dataset.deleteMemory);render();return true}
 if(b.dataset.cancelSession){const session=state.sessions.find(s=>s.id===b.dataset.cancelSession);await putPrivate('sessions',{...session,status:'dismissed'},session.id);return true}
 if(b.dataset.discover){state.craving='Something different, '+b.dataset.discover;state.wants=[];state.rejectedDishIds=[];$('#craving').value=state.craving;showView('tonight');toast('Your table is using this dish’s food cues.');return true}
 }catch(e){toast(e.message);return true}return false;
}
function ensureOption(selector,value,label){const el=$(selector);if(![...el.options].some(o=>o.value===String(value)))el.add(new Option(label,String(value)))}
function installStudioEvents(){
 $('#cravingForm').onsubmit=e=>{e.preventDefault();state.craving=$('#craving').value;state.wants=[];state.removedWants=[];state.avoid=[];state.lighter=false;state.rejectedDishIds=[];const parsed=interpretCraving(state.craving,context());state.diners=parsed.diners;state.budget=parsed.budget;state.mode=parsed.mode;state.hunger=parsed.hunger;$('#hunger').value=state.hunger;ensureOption('#diners',state.diners,`${state.diners} diners`);ensureOption('#budget',state.budget,money(state.budget));$('#diners').value=String(state.diners);$('#budget').value=String(state.budget);$('#mealMode').value=state.mode;$('#mealStage').classList.remove('changed');void $('#mealStage').offsetWidth;$('#mealStage').classList.add('changed');render()};
 $('#diners').onchange=e=>{state.diners=+e.target.value;render()};$('#mealMode').onchange=e=>{state.mode=e.target.value;render()};$('#companion').onchange=e=>{state.otherWants=e.target.value?[e.target.value]:[];render()};
 document.addEventListener('change',e=>{try{if(e.target.id==='swapAnchor'){selectedPlan=swapMeal(selectedPlan,e.target.value,studio.candidates,studio.intent);renderPlan()}if(e.target.id==='extraDish'&&e.target.value){const d=studio.candidates.find(d=>d.id===e.target.value);if(d&&selectedPlan.items.length<4){const next=[...selectedPlan.items,{...d,slot:d.knowledge.role==='accompaniment'?'accompaniment':'contrast'}],total=next.every(i=>i.price!==null&&i.listed)?next.reduce((n,i)=>n+i.price,0):null;if(studio.intent.budget&&total!==null&&total>studio.intent.budget)throw new Error('This combination exceeds your listed-price budget.');selectedPlan.items=next;selectedPlan.total=total;selectedPlan.targetKey=`${selectedPlan.restaurantId}__${next.map(i=>i.dishId).sort().join('_')}`;renderPlan()}}}catch(e){toast(e.message)}});
}
