// Fictional public sample. These are not Sachit or Shalini's discussions.
export function sampleState(){
 const t='2026-10-01T09:00:00.000Z',base={createdAt:t,updatedAt:t,revision:1};
 return {
  threads:[{...base,id:'sample-discussion',title:'Could everyday expertise become a small business?',summary:'Explore a repeatable service, learn what people will pay for, then automate the work that repeats.',status:'active',authorName:'Alex · sample',createdBy:'sample-alex'}],
  messages:[{...base,id:'sample-thought',threadId:'sample-discussion',text:'People keep asking us to help organise their work. Could we turn that into something useful they come back for?',kind:'thought',authorName:'Alex · sample',createdBy:'sample-alex'},{...base,id:'sample-reply',threadId:'sample-discussion',text:'I would start with one repeated problem. We should compare a service, a reusable kit and a short workshop before choosing.',kind:'thought',authorName:'Sam · sample',createdBy:'sample-sam'}],
  branches:[{...base,id:'sample-service',threadId:'sample-discussion',sourceMessageId:'sample-thought',title:'A monthly workflow service',hypothesis:'A small team will pay monthly to remove a recurring admin task.',customer:'Independent service businesses',offer:'One process maintained each month',assumptions:'The problem repeats and the owner values outside help.',openQuestions:'Which task is painful enough to pay for?',demand:'Unverified — ask five owners',access:'Direct introductions',repeatability:'Monthly, if the task repeats',economics:'Estimate pending customer interviews',effort:'Hands-on delivery initially',automation:'Automate repeated steps after two cycles',uncertainty:'Willingness to pay',status:'exploring',authorName:'Alex · sample',createdBy:'sample-alex'},{...base,id:'sample-kit',threadId:'sample-discussion',sourceMessageId:'sample-reply',title:'A ready-to-use planning kit',hypothesis:'A practical template can solve the same problem with less ongoing delivery.',customer:'Solo business owners',offer:'Templates and a setup guide',demand:'Unverified',access:'Audience or distribution partner needed',repeatability:'Possible updates, not yet recurring demand',economics:'Price and distribution costs unknown',effort:'More initial production',automation:'Delivery can be automated',uncertainty:'Discovery and repeat purchases',status:'exploring',authorName:'Sam · sample',createdBy:'sample-sam'},{...base,id:'sample-session',threadId:'sample-discussion',parentId:'sample-service',title:'Test it in a paid working session',hypothesis:'One working session reveals the real process and a willingness to pay.',customer:'One business owner',offer:'Map and improve a recurring workflow together',demand:'To be tested',access:'One introduction',repeatability:'Unknown',economics:'Illustrative test only',effort:'One session',automation:'Observe first',uncertainty:'Will the improvement matter?',status:'shortlisted',authorName:'Alex · sample',createdBy:'sample-alex'}],
  findings:[{...base,id:'sample-finding',threadId:'sample-discussion',branchId:'sample-kit',title:'Distribution is still an open question',summary:'A reusable kit may reduce delivery work, but no acquisition channel has been validated. Test access to buyers before investing in production.',stance:'challenges',evidenceType:'inference',sourceUrl:'',authorName:'Example agent · sample',createdBy:'sample-agent',origin:'agent'},{...base,id:'sample-outside-finding',threadId:'',branchId:'',taskId:'sample-open-task',title:'A recurring problem is more useful than a fashionable category',summary:'This invented example suggests looking for repeated work before choosing a product format. It is a demonstration of a research finding, not market evidence.',stance:'neutral',evidenceType:'inference',sourceUrl:'https://example.org',sourceTitle:'Illustrative link · example.org',authorName:'Example agent · sample',createdBy:'sample-agent',origin:'agent'}],
  researchTasks:[{...base,id:'sample-task',threadId:'sample-discussion',branchId:'sample-service',question:'Which recurring admin jobs do independent businesses already pay someone to handle?',scope:'focused',status:'queued',authorName:'Alex · sample',createdBy:'sample-alex'},{...base,id:'sample-open-task',threadId:'',branchId:'',question:'Look beyond our starting ideas for recurring customer problems.',scope:'open',status:'completed',resultSummary:'Illustrative result only: repeated work may offer a more useful starting point than a broad sector.',authorName:'Alex · sample',createdBy:'sample-alex'}],
  decisions:[{...base,id:'sample-decision',threadId:'sample-discussion',branchId:'sample-session',outcome:'shortlisted',reason:'A small paid session can test demand and reveal the real workflow before we build a service.',revisitWhen:'After the first three conversations',authorName:'Alex · sample',createdBy:'sample-alex'}],
  experiments:[{...base,id:'sample-experiment',threadId:'sample-discussion',branchId:'sample-session',title:'Ask three owners for a paid pilot',hypothesis:'At least one owner will pay to improve a repeated workflow.',method:'Show one specific offer in three direct conversations.',successCriterion:'One paid pilot, plus a clearly defined repeated problem.',status:'planned',result:'',learning:'',nextStep:'',authorName:'Alex · sample',createdBy:'sample-alex'}],
  discoveries:[{...base,id:'sample-signal',title:'An owner repeats the same planning task each week',summary:'Fictional observation used to show how outside evidence enters the studio. Validate the problem before drawing conclusions.',status:'new',sourceUrl:'https://example.org',initialThought:'Could a narrow recurring problem be worth paying to solve?',createdBy:'sample-alex',authorName:'Alex · sample'}],patterns:[{...base,id:'sample-pattern',title:'Repeated work may hide a service opportunity',summary:'An illustrative pattern only. One observation is not proof of a market.',derivedFrom:['sample-signal'],status:'exploring'}],opportunities:[{...base,id:'sample-opportunity',title:'A general-purpose planning app',summary:'An invented alternative retained to demonstrate a recorded rejection.',offer:'One app for every kind of business planning',customer:'Too broad to validate yet',status:'rejected',decisionReason:'Start with a specific paid problem before committing to a large product.',derivedFrom:['sample-signal'],risks:'No validated acquisition path or willingness to pay.'}],runs:[{...base,id:'sample-run',startedAt:t,status:'completed',summary:'Invented sample run. No real market scan was performed.',discoveryCount:1}],members:[{id:'sam@example.invalid',email:'sam@example.invalid',name:'Sam · sample',role:'editor',invitedAt:t}]
 };
}
