// Fictional interface fixtures only. Never uploaded to a real workspace.
import {DEFAULT_SETTINGS,indiaDay} from './core.mjs';
export function demoState(){
 const now=new Date().toISOString(),topics=['AI & agents','Robotics','Science','Business','AI & agents'];
 const titles=['When an agent can explain what it changed','A small mechanism. An entirely different kind of motion.','A discovery is more useful when the evidence is visible','What a business result changes—and what it does not','A useful question can outlive today’s headline'];
 const items=titles.map((title,i)=>({id:`sample${i}`,title,topic:topics[i],region:i%2?'india':'global',summary:['Most launch coverage stops at capability. This fictional example instead leaves room for an implementation question: what evidence would make an autonomous change trustworthy?','A place for questions about form, energy and movement. Capture the possibility, then connect it to an experiment.','Keep the result, the limitations and the original source close together. A compelling headline should not stand in for evidence.','Separate reported facts from interpretation. Preserve the context you need before drawing a conclusion.','The collection ends after five items. Interesting questions can continue in your threads.'][i],why:'Fictional selection explanation. Your declared direction remains under your control.',action:'Explore the interface, not this fictional example as news.',source:'Interface example',url:'',publishedAt:now,image:{kind:'concept',alt:'Fictional topic concept sketch, not a photograph'},evidence:{classification:i===1||i===2?'research-result':i===3?'reported-claim':'official-announcement',basis:'Synthetic evidence annotation for interface testing. This is not an actual announcement or research result.',limitations:'No real claim is being made. These examples must never enter your private feed.',sources:[]}}));
 const feedback=[{id:'sample1',itemId:'sample1',reaction:'useful',note:'',itemTitle:titles[1],topic:topics[1],source:'Interface example',url:'',createdAt:now},{id:'sample2',itemId:'sample2',reaction:'thought',note:'What did the experiment actually measure?',itemTitle:titles[2],topic:topics[2],source:'Interface example',url:'',createdAt:now}];
 return {settings:structuredClone(DEFAULT_SETTINGS),paused:false,preferenceVersion:1,generation:'demo',captures:[{id:'note1',text:'Could a news item become a small experiment rather than another saved link?',kind:'question',threadId:'thread1',createdAt:now}],threads:[{id:'thread1',title:'How can information lead to something I actually build?',shareWithAgent:false,createdAt:now}],feedback,runs:[],edition:{id:indiaDay(now),publishedAt:now,method:'demo',explanation:'Fictional layout examples, not news or evidence of a running agent.',items},reflections:[{id:indiaDay(now),date:indiaDay(now),status:'partial',generation:'demo',summary:'In this fictional sample, one mechanism was marked useful and another example prompted a question about evidence.',sourceRefs:feedback.map(({itemId,createdAt,reaction})=>({itemId,createdAt,reaction})),observations:[{title:'A mechanism caught your interest',detail:'One useful reaction is a limited positive signal—not proof of a permanent preference.',itemIds:['sample1']},{title:'A request for evidence',detail:'The shared question asks what was measured. It does not establish agreement or disagreement with the example.',itemIds:['sample2']}],followUps:[{question:'What did the experiment measure?',response:'This is fictional sample content. A live response would identify the measurement, controls and limitations, with source links.',status:'open',sources:[]}],adjustments:'A live agent could seek better measurement detail while preserving the declared topic mix.',limitation:'Fictional sample. No personal inference or real behaviour is represented.'}]};
}
