import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';
import {safeUrl,canonicalUrl,validateSettings,validateEdition,DEFAULT_SETTINGS,TOPICS} from './core.mjs';
const now=Date.parse('2026-09-27T04:00:00Z');
const items=Array.from({length:5},(_,i)=>({id:`item${i}`,title:`Item ${i}`,summary:'Evidence summary.',why:'Declared topic match.',action:'Read the original source.',source:`Source ${i}`,url:`https://example.com/${i}`,publishedAt:new Date(now-i*10000).toISOString(),topic:TOPICS[i%4],region:i%2?'global':'india'}));
test('reject executable and credentialed URLs',()=>{for(const u of ['javascript:alert(1)','https://secret@example.com','data:text/html,x'])assert.equal(safeUrl(u),'');});
test('canonical links remove tracking',()=>assert.equal(canonicalUrl('https://example.com/a/?utm_source=x#p'),'https://example.com/a'));
test('require a declared topic',()=>assert.throws(()=>validateSettings({...DEFAULT_SETTINGS,topics:[]})));
test('reject unsupported preference expansion',()=>assert.throws(()=>validateSettings({...DEFAULT_SETTINGS,topics:['Politics']})));
test('deduplicate declared topics',()=>assert.equal(validateSettings({...DEFAULT_SETTINGS,topics:[TOPICS[0],TOPICS[0]]}).topics.length,1));
test('validate five independently researched items',()=>assert.equal(validateEdition({items},now).items.length,5));
test('insufficient items fail rather than filling',()=>assert.throws(()=>validateEdition({items:items.slice(0,3)},now)));
test('duplicate sources fail',()=>assert.throws(()=>validateEdition({items:Array(5).fill(items[0])},now)));
test('duplicate item IDs fail',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,id:'same'}))},now)));
test('future publication dates fail',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,publishedAt:'2099-01-01'}))},now)));
test('invalid source URL fails',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,url:'javascript:x'}))},now)));
test('action notes and safe image metadata survive validation',()=>{const e=validateEdition({items:items.map(i=>({...i,imageUrl:'https://example.com/picture.jpg'}))},now);assert.equal(e.items[0].action,items[0].action);assert.equal(e.items[0].imageUrl,'https://example.com/picture.jpg');});
test('invalid image URLs fail',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,imageUrl:'javascript:x'}))},now)));
test('published method is external-agent reviewed',()=>assert.equal(validateEdition({items},now).method,'agent-reviewed'));
test('client and adapter use default Firestore',()=>{assert.match(readFileSync('personal-app/app.mjs','utf8'),/getFirestore\(app\)/);assert.match(readFileSync('personal-functions/runtime.cjs','utf8'),/db:getFirestore\(app\)/);assert.equal(JSON.parse(readFileSync('firebase.personal.json')).firestore[0].database,'(default)');});
test('duplicate news collector is removed',()=>{assert.equal(existsSync('.github/workflows/personal-curation.yml'),false);assert.equal(existsSync('personal-functions/curate.mjs'),false);});
