import {mkdir,writeFile,access} from 'node:fs/promises';import path from 'node:path';
const [slug,name]=process.argv.slice(2);if(!/^[a-z][a-z0-9-]{2,32}$/.test(slug||'')||!name||name.length>80)throw Error('Usage: node personal-harness/create-app.mjs <lowercase-slug> "App name"');
const dir=path.resolve(import.meta.dirname,'..','apps',slug);try{await access(dir);throw Error('An app already exists at this path.');}catch(e){if(e.code!=='ENOENT')throw e;}
await mkdir(dir,{recursive:true});const title=name.replace(/[&<>"']/g,'');
const files={
 'app.contract.json':JSON.stringify({id:slug,name,purpose:'DEFINE BEFORE IMPLEMENTATION',status:'draft',private:true,allowedData:[],agentResponsibilities:[],successCriteria:[],designDirection:'Define a product-specific interface; do not clone the news reader.',deployment:{project:'pti-app-2ab59',site:`pti-app-2ab59-${slug}`}},null,2)+'\n',
 'index.html':`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f4ee"><link rel="manifest" href="./manifest.webmanifest"><title>${title}</title><main><h1>${title}</h1><p>Private-app scaffold. Define the app contract, authentication and data boundaries before deployment.</p></main><script type="module" src="./app.mjs"></script></html>\n`,
 'app.mjs':`// Add the experience only after completing app.contract.json. No implicit tracking or AI calls.\nif ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(console.error);\n`,
 'sw.js':`// Cache only static, explicitly named assets. Never cache private API or auth responses.\nconst CACHE='${slug}-shell-v1';\nself.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(['./','./app.mjs']))));\n`,
 'manifest.webmanifest':JSON.stringify({name,short_name:name.slice(0,20),id:'/',start_url:'/',display:'standalone',background_color:'#f6f4ee',theme_color:'#f6f4ee',icons:[]},null,2)+'\n',
 'AGENTS.md':'Read ../../personal-harness/README.md, then app.contract.json. This is an undeployed starter, not an accepted app. Define its purpose, permitted data, icon assets, distinct design, authentication, rules and acceptance tests. Inspect actual mobile/desktop renders. Deploy only its isolated Hosting site. Never change existing PTI apps to make this starter work.\n'
};for(const [file,content]of Object.entries(files))await writeFile(path.join(dir,file),content,{flag:'wx'});console.log(`Created ${path.relative(process.cwd(),dir)}. No deployment or private-data access enabled.`);
