import test from 'node:test';
import assert from 'node:assert/strict';
import {validateEdition,validateReflection,reflectionMatchesFeedback,indiaDay,TOPICS} from './core.mjs';
const now=Date.parse('2026-09-29T10:00:00Z');
const items=Array.from({length:5},(_,i)=>({id:`test${i}`,title:`Synthetic ${i}`,summary:'An explicit synthetic test.',why:'Contract test.',source:'Test source',url:`https://example.com/${i}`,publishedAt:'2026-09-28',topic:TOPICS[i%4],region:i%2?'global':'india'}));
const source={label:'Original source',url:'https://example.com/evidence',kind:'primary'};
const evidence={classification:'official-announcement',sources:[source],basis:'The issuer made an announcement.',limitations:'Independent performance has not been established.'};
const feedback=[{itemId:'test0',reaction:'useful',createdAt:'2026-09-29T08:00:00Z'}];
const reflection={date:'2026-09-29',status:'partial',summary:'One explicit useful response.',sourceRefs:feedback,observations:[{title:'A recorded response',detail:'One item was marked useful.',itemIds:['test0']}],followUps:[],adjustments:'Preserve the declared topic mix.'};
test('structured evidence survives publication',()=>assert.deepEqual(validateEdition({items:items.map(i=>({...i,evidence}))},now).items[0].evidence,evidence));
test('unsupported evidence verdict is rejected',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,evidence:{...evidence,classification:'propaganda'}}))},now)));
test('limitations are required rather than invented certainty',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,evidence:{...evidence,limitations:''}}))},now)));
test('asset query strings are preserved',()=>{const url='https://example.com/image.webp?utm_token=signed&signature=abc';assert.equal(validateEdition({items:items.map(i=>({...i,imageUrl:url}))},now).items[0].imageUrl,url);});
test('source image provenance survives',()=>{const image={kind:'source',url:'https://example.com/a.png',sourcePageUrl:'https://example.com/a',alt:'A published diagram',credit:'Author',note:'Not an event photograph'};assert.deepEqual(validateEdition({items:items.map(i=>({...i,image}))},now).items[0].image,image);});
test('source images require their page',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,image:{kind:'source',url:'https://example.com/a.png',alt:'Diagram'}}))},now)));
test('generated images cannot invent a missing asset',()=>assert.throws(()=>validateEdition({items:items.map(i=>({...i,image:{kind:'generated',alt:'Illustration'}}))},now)));
test('labelled concept sketch needs no external image',()=>assert.equal(validateEdition({items:items.map(i=>({...i,image:{kind:'concept',alt:'Topic diagram, not an event photograph'}}))},now).items[0].image.kind,'concept'));
test('date-only publication stays date-only',()=>assert.equal(validateEdition({items},now).items[0].publishedAt,'2026-09-28'));
test('India day handles UTC boundary',()=>assert.equal(indiaDay('2026-09-28T19:00:00Z'),'2026-09-29'));
test('partial reflection validates against actual feedback',()=>{const r=validateReflection(reflection,now);assert(reflectionMatchesFeedback(r,feedback));});
test('today cannot be claimed as a completed day',()=>assert.throws(()=>validateReflection({...reflection,status:'complete'},now)));
test('unsupported reflection observation is rejected',()=>assert.throws(()=>validateReflection({...reflection,observations:[{title:'Invalid',detail:'Invented',itemIds:['unobserved']}]},now)));
test('duplicate response references cannot inflate evidence',()=>assert.throws(()=>validateReflection({...reflection,sourceRefs:[...feedback,...feedback]},now)));
test('deletion hides prior inference',()=>assert.equal(reflectionMatchesFeedback(reflection,[]),false));
test('changed reaction hides prior inference',()=>assert.equal(reflectionMatchesFeedback(reflection,[{...feedback[0],reaction:'less'}]),false));
test('edited note timestamp invalidates prior inference',()=>assert.equal(reflectionMatchesFeedback(reflection,[{...feedback[0],createdAt:'2026-09-29T08:01:00Z'}]),false));
test('new same-day response invalidates incomplete synthesis',()=>assert.equal(reflectionMatchesFeedback(reflection,[...feedback,{itemId:'test1',reaction:'thought',createdAt:'2026-09-29T08:30:00Z'}]),false));
test('other-day records do not alter the selected day',()=>assert(reflectionMatchesFeedback(reflection,[...feedback,{itemId:'test1',reaction:'thought',createdAt:'2026-09-28T08:00:00Z'}])));
test('an edition can carry a validated reflection',()=>assert.equal(validateEdition({items,reflection},now).reflection.sourceRefs.length,1));
