name: Deploy Angular App to Firebase Hosting

on:
  push:
    branches:
      - main  # Trigger workflow when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest code from GitHub
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use latest stable version

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: cd pti-app && npm install  # Manually change directory

      # Step 4: Build Angular App
      - name: Build Angular App
        run: cd pti-app && npm run build -- --configuration production  # Manually change directory

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
